# Generated by Django 5.1.7 on 2025-04-19 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temp_high', models.FloatField(help_text='High temperature in Fahrenheit')),
                ('temp_low', models.FloatField(help_text='Low temperature in Fahrenheit')),
                ('precipitation_chance', models.IntegerField(help_text='Chance of precipitation in percentage')),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('shoes', 'Shoes'), ('dress', 'Dress'), ('jacket', 'Jacket'), ('accessory', 'Accessory')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing_items/')),
                ('weather_suitability', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cool', 'Cool'), ('cold', 'Cold'), ('rainy', 'Rainy')], max_length=20)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black')], max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('formality', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_worn', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temp_high', models.FloatField()),
                ('temp_low', models.FloatField()),
                ('precipitation_chance', models.FloatField()),
                ('humidity', models.FloatField()),
                ('conditions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='wardrobe_we_date_f6bf3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WearLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_worn', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.ManyToManyField(to='wardrobe.clothingitem')),
                ('weather_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wardrobe.weatherlog')),
            ],
            options={
                'ordering': ['-date_worn'],
                'indexes': [models.Index(fields=['date_worn'], name='wardrobe_we_date_wo_a8e42a_idx')],
            },
        ),
    ]
