services:
  - type: web
    name: closet-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: closet-app-db
          property: connectionString
    healthCheckPath: /api/health/
    autoDeploy: true

  - type: static
    name: closet-app-frontend
    env: node
    # Last updated: 2024-04-19 13:45
    buildCommand: cd src/frontend && npm install && npm run build
    publishDir: src/frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://closet-app-backend.onrender.com
    autoDeploy: true

databases:
  - name: closet-app-db
    databaseName: closet_app
    user: closet_app
    plan: free 