services:
  - type: web
    name: closet-app-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd src/frontend
      npm ci
      npm run build
      cd ../..
      python manage.py collectstatic --noinput --verbosity 2 --clear
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: closet-app-db
          property: connectionString
    healthCheckPath: /api/health/
    autoDeploy: true

databases:
  - name: closet-app-db
    databaseName: closet_app
    user: closet_app
    plan: free